# 新时代个人成长与创业8原则 - 主要原则数据
# 转换时间: 2025-09-09T03:15:48.903Z
# 来源: docs/research/250905-8原则.md
# 用途: Growth系统原则数据源

[metadata]
title = "新时代个人成长与创业8原则"
version = "1.0"
total_principles = 8
generated_at = "2025-09-09T03:15:48.904Z"
source_file = "250905-8原则.md"


[[principles]]
id = "principle_1"
order = 1
name = "你，就是最值得投资的生意"
assertion = "对年轻人来说，最好的生意就是“做自己”。"
concept = "你的经历、兴趣、成长就是独一无二的“赛道”。创业就是把解决自己问题的方法，卖给“过去的自己”。"
practices = [
    "先定义理想生活，再找赚钱方式。",
    "把成长过程和经验分享出来，形成专业与价值。",
    "走高杠杆路径：从内容 → 服务 → 产品 → 公司。",
]
antipatterns = [
    "盲目跟风只会变成“另一份 996”，既累又赚不到自由。",
]

[[principles]]
id = "principle_2"
order = 2
name = "注意力 > 时间 > 金钱"
assertion = "注意力是你最宝贵的资源。"
concept = "金钱能再赚，时间不可逆，但注意力决定了人生走向。被短视频和八卦劫持的人，失去创造价值的能力。"
practices = [
    "给注意力定价，用时薪衡量投入是否值得。",
    "掌控环境，屏蔽无用信息。",
    "用价值观来聚焦长期重要的事。",
]
antipatterns = [
    "注意力被掠夺，专注力低于 45 分钟的人，将被淘汰。",
]

[[principles]]
id = "principle_3"
order = 3
name = "对自己的人生负 100% 责任"
assertion = "我，且只有我，对我的人生负全责。"
concept = "停止抱怨，停止推责。成长与财富的源头只能从自己身上挖掘。"
practices = [
    "戒掉抱怨，把精力投向行动。",
    "向内求索：我能提供什么价值？",
    "主动进化：预测未来趋势，提前行动。",
]
antipatterns = [
    "抱怨是“弱者病毒”，会让你失去主导权，陷入受害者心态。",
]

[[principles]]
id = "principle_4"
order = 4
name = "元认知是大脑的操作系统"
assertion = "没有元认知，你是大脑的奴隶；拥有它，你才是主人。"
concept = "元认知就是“觉察自己的思维”。它让你能审视想法，升级心智操作系统，避免被情绪和本能控制。"
practices = [
    "冥想，训练对注意力的掌控。",
    "每日反思，记录并修正决策逻辑。",
    "用写作打磨思维，让模糊变清晰。",
]
antipatterns = [
    "缺乏元认知，你的决定只是情绪的自动反应。",
]

[[principles]]
id = "principle_5"
order = 5
name = "创业哲学——先生活，后赚钱"
assertion = "创业是为了过想要的生活，而不是换一个地方 996。"
concept = "新型创业逻辑是：成长 → 分享 → 变现。工作与生活不分割，因为你靠“做自己”赚钱。"
practices = [
    "明确理想生活。",
    "服务“过去的自己”，把解决方案产品化。",
    "用“T型内容”策略：专业+个人。",
]
antipatterns = [
    "把赚钱当唯一目标，结果就是牺牲生活，被生意反噬。",
]

[[principles]]
id = "principle_6"
order = 6
name = "个人商业模式要进化"
assertion = "财富自由是从卖时间到买时间的跃迁。"
concept = "三部曲——①卖时间（打工）②卖产品（批量复制）③买时间（组织/投资）。"
practices = [
    "第一站：打工时重视学习而不是薪水。",
    "第二站：把技能产品化，打造睡后收入。",
    "第三站：通过创业/投资，放大时间与金钱。",
]
antipatterns = [
    "长期停留在卖时间，意味着“手停口停”。",
]

[[principles]]
id = "principle_7"
order = 7
name = "从建立受众开始"
assertion = "对新手来说，最安全的创业起点是建立自己的受众。"
concept = "受众是信任的积累，未来所有项目的流量池。它是一种零成本、高杠杆的启动方式。"
practices = [
    "分享所学，倒逼自己成长。",
    "用费曼学习法发现盲区。",
    "从服务类产品开始变现。",
]
antipatterns = [
    "没有受众就做电商或高门槛项目，风险极高。",
]

[[principles]]
id = "principle_8"
order = 8
name = "长期主义：聪明模仿 + 定投成长"
assertion = "模仿是学习框架，定投是靠复利取胜。"
concept = "模仿成功案例的结构，而非复制内容；定投不仅是理财，更是知识、技能、健康和关系的复利积累。"
practices = [
    "建立素材库，学习高手的框架。",
    "小步快跑，迭代出个人风格。",
    "锁定一门技能，至少投入 1000 小时。",
]
antipatterns = [
    "只做被动消费者，追求速成，会死在复利的“拐点”前。",
]
